apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wolfns
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer
