apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: wolfns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: marcusvbrangel/wolfstore-backend:1.0
          ports:
            - containerPort: 80
