apiVersion: v1
kind: Service
metadata:
  name: wolfstore-backend-service
  namespace: wolfns
spec:
  selector:
    app: wolfstore-backend
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 80
  type: ClusterIP
