apiVersion: apps/v1
kind: Deployment
metadata:
  name: wolfstore-products-deployment
  namespace: wolfns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wolfstore-products
      type: backend
      technology: spring-boot
  template:
    metadata:
      labels:
        app: wolfstore-products
        type: backend
        technology: spring-boot
    spec:
      containers:
        - name: wolfstore-products
          image: marcusvbrangel/wolfstore-products:1.0.7
          ports:
            - containerPort: 8080
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: wolfstore-products
                  type: backend
                  technology: spring-boot
              topologyKey: "kubernetes.io/hostname"