apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wolfns
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 80
  type: LoadBalancer
